#+LATEX_CLASS: book-noparts
#+LATEX_CLASS_OPTIONS: [a4paper, openany]
#+LATEX_COMPILER: pdflatex
#+OPTIONS: toc:nil \n:nil
#+LATEX_HEADER: \input{baseHeader.tex}
#+TITLE:
#+AUTHOR:
#+DATE:
#+LATEX_HEADER: \titel{\textbf{Bachelorproject}} \undertitel{Cryptographic library for FPGA's} \opgave{Bachelor Project} \forfatter{Jacob Herbst(mwr148), Jonas Flach Jensen (sjm233)} \dato{14 june 2021} \vejleder{Advisor: Kenneth Skovhede}
\maketitle

#+BEGIN_EXPORT latex
\chapter*{\begin{center}\begin{normalsize}Abstract\end{normalsize}\end{center}}
\begin{changemargin}{1.5cm}{1.5cm}
Computer security and cryptography is ubiquitous and is a critical aspect of computer science. Often cryptography is handled in the CPU as with the general majority of computing. Still, in some cases, CPUs might be a suboptimal solution, for instance, when low power consumption is critical. In such a case, a Field Programmable Gate Array (FPGA) is a good alternative. This report will present a library of four cryptographic functions designed for FPGA devices: MD5, SHA256, AES, and ChaCha20. We will present the underlying algorithm of the four functions and how we have implemented these using a high-level programming model Synchronous Message Exchange (SME) in C\# instead of the usual approach of using a Hardware Description Language(HDL). We will further present how we, by pipelining, have achieved performance comparable to a CPU of a similar price range at much lower power consumption. In the process, we have tried investigating different parts of FPGA programming and how this can be applied in SME to see if it would further improve performance. We were, however, not able to achieve this and hence included some reflection on how approachable FPGA programming is using a high-level model such as SME. Code for the project can be found at:\\
\url{https://github.com/Spatenheinz/Bachelor}
\end{changemargin}
#+END_EXPORT

\newpage

\tableofcontents
\listofillustrations

#+INCLUDE: "introduction.org"

#+INCLUDE: "Background/background.org"

#+INCLUDE: "Implementation/implementation.org"

#+INCLUDE: "Benchmarks/benchmarks.org"

#+INCLUDE: "discussion.org"

#+INCLUDE: "conclusion.org"

# #bibliography
\bibliographystyle{unsrturl}
\bibliography{ref}

\begin{appendix}
#+INCLUDE: "Appendix.org"
* AES Look Up Table
:PROPERTIES:
:UNNUMBERED: nil
:CUSTOM_ID: AESLUT
:END:
#+BEGIN_EXPORT latex
\begin{table}[!htb]
\centering
\captionsetup{width=.8\linewidth}
\begin{tabular}{c || c c c c c c c c c c c c c c c c}
\hline
   & 00 & 01 & 02 & 03 & 04 & 05 & 06 & 07 & 08 & 09 & 0a & 0b & 0c  & 0d & 0e & 0f\\
\hline
00 & 63 & 7c & 77 & 7b & f2 & 6b & 6f & c5 & 30 & 01 & 67 & 2b & fe  & d7 & ab & 76\\
10 & ca & 82 & c9 & 7d & fa & 59 & 47 & f0 & ad & d4 & A2 & af & 9c  & a4 & 72 & c0\\
20 & b7 & fd & 93 & 26 & 36 & 3f & f7 & cc & 34 & a5 & E5 & f1 & 71  & d8 & 31 & 15\\
30 & 04 & c7 & 23 & c3 & 18 & 96 & 05 & 9a & 07 & 12 & 80 & e2 & eb  & 27 & b2 & 75\\
40 & 09 & 83 & 2c & 1a & 1b & 6e & 5a & a0 & 52 & 3b & D6 & b3 & 29  & e3 & 2f & 84\\
50 & 53 & d1 & 00 & ed & 20 & fc & b1 & 5b & 6a & cb & Be & 39 & 4a  & 4c & 58 & cf\\
60 & d0 & ef & aa & fb & 43 & 4d & 33 & 85 & 45 & f9 & 02 & 7f & 50  & 3c & 9f & a8\\
70 & 51 & a3 & 40 & 8f & 92 & 9d & 38 & f5 & bc & b6 & Da & 21 & 10  & ff & f3 & d2\\
80 & cd & 0c & 13 & ec & 5f & 97 & 44 & 17 & c4 & a7 & 7e & 3d & 64  & 5d & 19 & 73\\
90 & 60 & 81 & 4f & dc & 22 & 2a & 90 & 88 & 46 & ee & B8 & 14 & de  & 5e & 0b & db\\
a0 & e0 & 32 & 3a & 0a & 49 & 06 & 24 & 5c & c2 & d3 & Ac & 62 & 91  & 95 & e4 & 79\\
b0 & e7 & c8 & 37 & 6d & 8d & d5 & 4e & a9 & 6c & 56 & F4 & ea & 65  & 7a & ae & 08\\
c0 & ba & 78 & 25 & 2e & 1c & a6 & b4 & c6 & e8 & dd & 74 & 1f & 4b  & bd & 8b & 8a\\
d0 & 70 & 3e & b5 & 66 & 48 & 03 & f6 & 0e & 61 & 35 & 57 & b9 & 86  & c1 & 1d & 9e\\
e0 & e1 & f8 & 98 & 11 & 69 & d9 & 8e & 94 & 9b & 1e & 87 & e9 & ce  & 55 & 28 & df\\
f0 & 8c & a1 & 89 & 0d & bf & e6 & 42 & 68 & 41 & 99 & 2d & 0f & b0  & 54 & bb & 16
\end{tabular}
\caption[AES Look Up Table]%
{AES Look Up Table. Every value is shown in hex}
\label{tab:AESTable}
\end{table}
#+END_EXPORT
* Modes of operations
:PROPERTIES:
:UNNUMBERED: nil
:CUSTOM_ID: MODES
:END:
\begin{figure}[H]
# \centering
\hspace*{-2cm}
\subfloat[Encryption \cite{wiki:ecb}]{\includegraphics[width=9cm]{ECB.png}}
\subfloat[Decryption \cite{wiki:ecbD}]{\includegraphics[width=9cm]{ECBD.png}}
\caption{Electronic Codebook (ECB) mode}
\label{fig:ECB}
\end{figure}
\begin{figure}[H]
# \centering
\hspace*{-2cm}
\subfloat[Encryption \cite{wiki:cbc}]{\includegraphics[width=9cm]{CBC.png}}
\subfloat[Decryption \cite{wiki:cbcD}]{\includegraphics[width=9cm]{CBCD.png}}
\caption{Cipher Block Chaining (CBC) mode}
\label{fig:CBC}
\end{figure}
\begin{figure}[H]
# \centering
\hspace*{-2cm}
\subfloat[Encryption \cite{wiki:ctr}]{\includegraphics[width=9cm]{CTR.png}}
\subfloat[Decryption \cite{wiki:ctrD}]{\includegraphics[width=9cm]{CTRD.png}}
\caption{Counter (CTR) mode}
\label{fig:CTR}
\end{figure}

\end{appendix}
